# Generated by Django 2.2.3 on 2020-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer_model', '0008_auto_20200412_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer_c2',
            name='numberOfCustomer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
